name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3

        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: "@nextrap"

      - name: Update npm
        run: npm update

      - name: Set package.json version from tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          npm version "$TAG" --no-git-tag-version

      - name: Install dependencies
        run: npm ci

     # - name: Run tests
     #   run: npm run test

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
